# Filebeat for log shipping (Linux/Windows)
filebeat.inputs:
  # Generic log example (Linux)
  - type: filestream
    enabled: true
    id: syslog-filestream
    paths:
      - /var/log/syslog
      - /var/log/messages
    parsers:
      - multiline:
          type: pattern
          pattern: '^\s'
          negate: false
          match: after

  # Nginx access/error example (uncomment if used)
  # - type: filestream
  #   enabled: true
  #   id: nginx-access
  #   paths: ["/var/log/nginx/access.log*"]
  # - type: filestream
  #   enabled: true
  #   id: nginx-error
  #   paths: ["/var/log/nginx/error.log*"]

# Modules (preferred over raw inputs for common services)
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

# Choose ONE output. Elasticsearch direct OR Logstash.
# ---- Elasticsearch (direct) ----
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # protocol: "https"
  # username: "elastic"
  # password: "changeme"
  index: "filebeat-%{+yyyy.MM.dd}"

# ---- Logstash (via :5044) ----
# output.logstash:
#   hosts: ["logstash:5044"]

setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

# Kibana for dashboards preloading (optional)
setup.kibana:
  host: "http://kibana:5601"

# Logging
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  rotateeverybytes: 10485760
