# Metricbeat for Linux/Windows hosts
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

# System module quick enable (inline). For per-host installs, use `metricbeat modules enable system`.
metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - memory
      - network
      - diskio
      - filesystem
      - fsstat
      - process
      - socket
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5

# Choose ONE output. Elasticsearch direct OR Logstash.
# ---- Elasticsearch (direct) ----
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # protocol: "https"
  # username: "elastic"
  # password: "changeme"

# ---- Logstash (via :5044) ----
# output.logstash:
#   hosts: ["logstash:5044"]

setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

# Kibana for dashboards preloading (optional)
setup.kibana:
  host: "http://kibana:5601"

# Logging
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  rotateeverybytes: 10485760
