version: '3.8'

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfiles/prometheus.Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  alertmanager:
    build:
      context: .
      dockerfile: Dockerfiles/alertmanager.Dockerfile
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ../prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ../prometheus/rules:/etc/alertmanager/rules
    restart: unless-stopped

  grafana:
    build:
      context: .
      dockerfile: Dockerfiles/grafana.Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/provisioning/:/etc/grafana/provisioning/
      - ../grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfiles/elasticsearch.Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    build:
      context: .
      dockerfile: Dockerfiles/kibana.Dockerfile
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped

  logstash:
    build:
      context: .
      dockerfile: Dockerfiles/logstash.Dockerfile
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ../elk/logstash/pipelines.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  esdata:
    driver: local
